export const ATKRSLIST=[
    {
        name:"sledge",
        width:530,
        top:-40,
        left:-195,
    },
    {
        name:"thatcher",
        width:450,
        top:-50,
        left:-140,
    },
    {
        name:"ash",
        width:600,
        top:-70,
        left:-215,
    },
    {
        name:"thermite",
        width:540,
        top:-45,
        left:-170,
    },
    {
        name:"twitch",
        width:530,
        top:-60,
        left:-185,
    },
    {
        name:"montagne",
        width:530,
        top:-65,
        left:-155,
    },
    {
        name:"glaz",
        width:530,
        top:-50,
        left:-160,
    },
    {
        name:"fuze",
        width:530,
        top:-45,
        left:-190,
    },
    {
        name:"blitz",
        width:500,
        top:-60,
        left:-160,
    },
    {
        name:"iq",
        width:490,
        top:-75,
        left:-165,
    },
    {
        name:"addnew",
        width:700,
        top:-30,
        left:-285,
    }
]

export const DFNDRSLIST=[
    {
        name:"smoke",
        width:510,
        top:-35,
        left:-200,
    },
    {
        name:"mute",
        width:510,
        top:-35,
        left:-165,
    },
    {
        name:"castle",
        width:510,
        top:-45,
        left:-165,
    },
    {
        name:"pulse",
        width:510,
        top:-30,
        left:-165,
    },
    {
        name:"doc",
        width:600,
        top:-80,
        left:-225,
    },
    {
        name:"rook",
        width:600,
        top:-50,
        left:-220,
    },
    {
        name:"kapkan",
        width:600,
        top:-50,
        left:-210,
    },
    {
        name:"tachanka",
        width:500,
        top:-40,
        left:-160,
    },
    {
        name:"jäger",
        width:500,
        top:-30,
        left:-185,
    },
    {
        name:"bandit",
        width:500,
        top:-50,
        left:-170,
    },
    {
        name:"addnew",
        width:700,
        top:-30,
        left:-285,
    }
]